RapChieuPhim/RapChieuPhim/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using RapChieuPhim.Areas.Admin.Models;
using RapChieuPhim.Areas.Admin.Data;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RapChieuPhim.Controllers
{
    public class TaiKhoanController : Controller
    {
        private readonly DPContext _context;

        public TaiKhoanController(DPContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login([Bind("Ten_dang_nhap", "Mat_khau")] TaiKhoanModel taikhoan)
        {

            var r = _context.TaiKhoanModel.Where(m => (m.Ten_dang_nhap == taikhoan.Ten_dang_nhap && m.Mat_khau == StringProcessing.CreateMD5Hash(taikhoan.Mat_khau))).ToList();
            if (r.Count == 0)
            {
                return View("Index");
            }
            var str = JsonConvert.SerializeObject(taikhoan);
            HttpContext.Session.SetString("taikhoan", str);
            if (r[0].Loai_tai_khoan == 1)
            {

                var url = Url.RouteUrl("areas", new { Controller = "Home", action = "Index", area = "admin" });
                return Redirect(url);
            }
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Create()
        {
            ViewData["NguoiDung_ID"] = new SelectList(_context.NguoiDungModel, "ID", "HoTen");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Ten_dang_nhap,Mat_khau,Loai_tai_khoan,NguoiDung_ID,Da_xoa")] TaiKhoanModel taiKhoanModel)
        {

            if (ModelState.IsValid)
            {
                taiKhoanModel.Mat_khau = StringProcessing.CreateMD5Hash(taiKhoanModel.Mat_khau);
                _context.Add(taiKhoanModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["NguoiDung_ID"] = new SelectList(_context.NguoiDungModel, "ID", "ID", taiKhoanModel.NguoiDung_ID);
            return View(taiKhoanModel);
        }


    }
}

RapChieuPhim/RapChieuPhim/Views/Shared/_CssPartial.cshtml
<head>
    <title>Cinema A Entertainment Category Flat Bootstarp Resposive Website Template | Home :: w3layouts</title>
    <link href="~/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <!-- Custom Theme files -->
    <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/js/jquery.min.js"></script>
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Cinema Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
    Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
</head>

RapChieuPhim/RapChieuPhim/Views/Shared/_FooterPartial.cshtml
<div class="footer">
    <h6>Disclaimer : </h6>
    <p class="claim">This is a freebies and not an official website, I have no intention of disclose any movie, brand, news.My goal here is to train or excercise my skill and share this freebies.</p>
    <a href="example@mail.com">example@mail.com</a>
    <div class="copyright">
        <p> Template by  <a href="http://w3layouts.com">  W3layouts</a></p>
    </div>
</div>

RapChieuPhim/RapChieuPhim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    @await Html.PartialAsync("_CssPartial.cshtml")
    @RenderSection("css", required: false)
</head>
<body>

    <div class="full">

        @RenderBody()

    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

RapChieuPhim/RapChieuPhim/Views/Shared/_MenuPartial.cshtml
<div class="menu">
    <ul>
        <li><a class="active" href="Home"><i class="home"></i></a></li>
        <li><a href="VideosPage"><div class="video"><i class="videos"></i><i class="videos1"></i></div></a></li>
        <li><a href="ReviewsPage"><div class="cat"><i class="watching"></i><i class="watching1"></i></div></a></li>
        <li><a href="BooksSticker"><div class="bk"><i class="booking"></i><i class="booking1"></i></div></a></li>
        <li><a href="ContactPage"><div class="cnt"><i class="contact"></i><i class="contact1"></i></div></a></li>
    </ul>
</div>

RapChieuPhim/RapChieuPhim/Views/Shared/_TaiKhoanFoodPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!--===============================================================================================-->
<script src="~/Login/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="~/Login/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="~/Login/vendor/bootstrap/js/popper.js"></script>
<script src="~/Login/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="~/Login/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="~/Login/vendor/daterangepicker/moment.min.js"></script>
<script src="~/Login/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="~/Login/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="~/Login/js/main.js"></script>

RapChieuPhim/RapChieuPhim/Views/Shared/_TaiKhoanHeadPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<title>Cinema XXII</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
<link rel="icon" type="image/png" href="~/Login/images/icons/favicon.ico" />
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Login/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Login/vendor/animate/animate.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Login/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Login/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Login/vendor/select2/select2.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Login/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Login/css/util.css">
<link rel="stylesheet" type="text/css" href="~/Login/css/main.css">
<!--===============================================================================================-->

RapChieuPhim/RapChieuPhim/Views/Shared/_TopHeaderPartial.cshtml
<div class="top-header">
    <div class="col-md-6 logo col-md-6">
        <a href="Home"><img src="~/images/logo.png" alt="" /></a>
        <p>Movie Theater</p>
    </div>
    <div class="col-md-6 news-right-grid">
        <div class="col-md-6"> </div>
        <div class="col-md-6">

            @if (@Model != null)
            {
                <p>@Model.Ten_dang_nhap</p>
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Đăng xuất</a>

            }
            else
            {
                <a class="nav-link text-dark" asp-area="" asp-controller="TaiKhoan" asp-action="Create">Đăng ký</a>
                <a href="#">/</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="TaiKhoan" asp-action="Index">Đăng nhập</a>
            }

        </div>
    </div>
    <div class="clearfix"></div>
</div>